# For local development. Images are kept in sync with production, but running services through
# Compose isn't recommended. The `deploy` profile only pins images production deploys.
services:
  postgres:
    # renovate: datasource=docker depName=flyio/postgres-flex
    image: postgres:18.1-alpine
    shm_size: 256m
    command: postgres -N 500
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  manticore:
    image: manticoresearch/manticore:28.4.4@sha256:e44d8c9ced8147e73421d3b86e138fbdd3f4fefbcc1cbe043db648fb1cc75a7b
    restart: always
    mem_limit: 2g
    volumes:
      - manticore_data:/var/lib/manticore
    ports:
      - 9306:9306
      - 9308:9308
  listmonk:
    image: listmonk/listmonk:v6.2.0@sha256:f535d59e14991337a9f2d570273685378ae86b0d7698c3e00da444e3bc205286
    profiles: [deploy]
volumes:
  postgres_data:
  manticore_data:
