defmodule Flirtual.Languages do
  # https://en.wikipedia.org/wiki/IETF_language_tag

  @languages [
    %{bcp_47: :ab, name: "Abkhaz"},
    %{bcp_47: :aa, name: "Afar"},
    %{bcp_47: :af, name: "Afrikaans"},
    %{bcp_47: :ak, name: "Akan"},
    %{bcp_47: :sq, name: "Albanian"},
    %{bcp_47: :am, name: "Amharic"},
    %{bcp_47: :ar, name: "Arabic"},
    %{bcp_47: :an, name: "Aragonese"},
    %{bcp_47: :hy, name: "Armenian"},
    %{bcp_47: :as, name: "Assamese"},
    %{bcp_47: :av, name: "Avaric"},
    %{bcp_47: :ae, name: "Avestan"},
    %{bcp_47: :ay, name: "Aymara"},
    %{bcp_47: :az, name: "Azerbaijani"},
    %{bcp_47: :bm, name: "Bambara"},
    %{bcp_47: :ba, name: "Bashkir"},
    %{bcp_47: :eu, name: "Basque"},
    %{bcp_47: :be, name: "Belarusian"},
    %{bcp_47: :bn, name: "Bengali"},
    %{bcp_47: :bi, name: "Bislama"},
    %{bcp_47: :bs, name: "Bosnian"},
    %{bcp_47: :br, name: "Breton"},
    %{bcp_47: :bg, name: "Bulgarian"},
    %{bcp_47: :my, name: "Burmese"},
    %{bcp_47: :ca, name: "Catalan"},
    %{bcp_47: :ch, name: "Chamorro"},
    %{bcp_47: :ce, name: "Chechen"},
    %{bcp_47: :ny, name: "Chichewa"},
    %{bcp_47: :zh, name: "Chinese"},
    %{bcp_47: :cu, name: "Church Slavonic"},
    %{bcp_47: :cv, name: "Chuvash"},
    %{bcp_47: :kw, name: "Cornish"},
    %{bcp_47: :co, name: "Corsican"},
    %{bcp_47: :cr, name: "Cree"},
    %{bcp_47: :hr, name: "Croatian"},
    %{bcp_47: :cs, name: "Czech"},
    %{bcp_47: :da, name: "Danish"},
    %{bcp_47: :dv, name: "Divehi"},
    %{bcp_47: :nl, name: "Dutch"},
    %{bcp_47: :dz, name: "Dzongkha"},
    %{bcp_47: :en, name: "English"},
    %{bcp_47: :eo, name: "Esperanto"},
    %{bcp_47: :et, name: "Estonian"},
    %{bcp_47: :ee, name: "Ewe"},
    %{bcp_47: :fo, name: "Faroese"},
    %{bcp_47: :fj, name: "Fijian"},
    %{bcp_47: :fi, name: "Finnish"},
    %{bcp_47: :fr, name: "French"},
    %{bcp_47: :ff, name: "Fula"},
    %{bcp_47: :gd, name: "Gaelic"},
    %{bcp_47: :gl, name: "Galician"},
    %{bcp_47: :lg, name: "Ganda"},
    %{bcp_47: :ka, name: "Georgian"},
    %{bcp_47: :de, name: "German"},
    %{bcp_47: :el, name: "Greek"},
    %{bcp_47: :gn, name: "Guaraní"},
    %{bcp_47: :gu, name: "Gujarati"},
    %{bcp_47: :ht, name: "Haitian"},
    %{bcp_47: :ha, name: "Hausa"},
    %{bcp_47: :he, name: "Hebrew"},
    %{bcp_47: :hz, name: "Herero"},
    %{bcp_47: :hi, name: "Hindi"},
    %{bcp_47: :ho, name: "Hiri Motu"},
    %{bcp_47: :hu, name: "Hungarian"},
    %{bcp_47: :is, name: "Icelandic"},
    %{bcp_47: :io, name: "Ido"},
    %{bcp_47: :ig, name: "Igbo"},
    %{bcp_47: :id, name: "Indonesian"},
    %{bcp_47: :ia, name: "Interlingua"},
    %{bcp_47: :ie, name: "Interlingue"},
    %{bcp_47: :iu, name: "Inuktitut"},
    %{bcp_47: :ik, name: "Inupiaq"},
    %{bcp_47: :ga, name: "Irish"},
    %{bcp_47: :it, name: "Italian"},
    %{bcp_47: :ja, name: "Japanese"},
    %{bcp_47: :jv, name: "Javanese"},
    %{bcp_47: :kl, name: "Kalaallisut"},
    %{bcp_47: :kn, name: "Kannada"},
    %{bcp_47: :kr, name: "Kanuri"},
    %{bcp_47: :ks, name: "Kashmiri"},
    %{bcp_47: :kk, name: "Kazakh"},
    %{bcp_47: :km, name: "Khmer"},
    %{bcp_47: :ki, name: "Kikuyu"},
    %{bcp_47: :rw, name: "Kinyarwanda"},
    %{bcp_47: :rn, name: "Kirundi"},
    %{bcp_47: :kv, name: "Komi"},
    %{bcp_47: :kg, name: "Kongo"},
    %{bcp_47: :ko, name: "Korean"},
    %{bcp_47: :ku, name: "Kurdish"},
    %{bcp_47: :kj, name: "Kwanyama"},
    %{bcp_47: :ky, name: "Kyrgyz"},
    %{bcp_47: :lo, name: "Lao"},
    %{bcp_47: :la, name: "Latin"},
    %{bcp_47: :lv, name: "Latvian"},
    %{bcp_47: :li, name: "Limburgish"},
    %{bcp_47: :ln, name: "Lingala"},
    %{bcp_47: :lt, name: "Lithuanian"},
    %{bcp_47: :lu, name: "Luba-Katanga"},
    %{bcp_47: :lb, name: "Luxembourgish"},
    %{bcp_47: :mk, name: "Macedonian"},
    %{bcp_47: :mg, name: "Malagasy"},
    %{bcp_47: :ms, name: "Malay"},
    %{bcp_47: :ml, name: "Malayalam"},
    %{bcp_47: :mt, name: "Maltese"},
    %{bcp_47: :gv, name: "Manx"},
    %{bcp_47: :mi, name: "Maori"},
    %{bcp_47: :mr, name: "Marathi"},
    %{bcp_47: :mh, name: "Marshallese"},
    %{bcp_47: :mn, name: "Mongolian"},
    %{bcp_47: :na, name: "Nauru"},
    %{bcp_47: :nv, name: "Navajo"},
    %{bcp_47: :ng, name: "Ndonga"},
    %{bcp_47: :ne, name: "Nepali"},
    %{bcp_47: :nd, name: "Northern Ndebele"},
    %{bcp_47: :se, name: "Northern Sami"},
    %{bcp_47: :nb, name: "Norwegian Bokmål"},
    %{bcp_47: :nn, name: "Norwegian Nynorsk"},
    %{bcp_47: :no, name: "Norwegian"},
    %{bcp_47: :ii, name: "Nuosu"},
    %{bcp_47: :oc, name: "Occitan"},
    %{bcp_47: :oj, name: "Ojibwe"},
    %{bcp_47: :or, name: "Oriya"},
    %{bcp_47: :om, name: "Oromo"},
    %{bcp_47: :os, name: "Ossetian"},
    %{bcp_47: :pi, name: "Pali"},
    %{bcp_47: :pa, name: "Panjabi"},
    %{bcp_47: :ps, name: "Pashto"},
    %{bcp_47: :fa, name: "Persian"},
    %{bcp_47: :pl, name: "Polish"},
    %{bcp_47: :pt, name: "Portuguese"},
    %{bcp_47: :qu, name: "Quechua"},
    %{bcp_47: :ro, name: "Romanian"},
    %{bcp_47: :rm, name: "Romansh"},
    %{bcp_47: :ru, name: "Russian"},
    %{bcp_47: :sm, name: "Samoan"},
    %{bcp_47: :sg, name: "Sango"},
    %{bcp_47: :sa, name: "Sanskrit"},
    %{bcp_47: :sc, name: "Sardinian"},
    %{bcp_47: :sr, name: "Serbian"},
    %{bcp_47: :sn, name: "Shona"},
    %{bcp_47: :sd, name: "Sindhi"},
    %{bcp_47: :si, name: "Sinhala"},
    %{bcp_47: :sk, name: "Slovak"},
    %{bcp_47: :sl, name: "Slovene"},
    %{bcp_47: :so, name: "Somali"},
    %{bcp_47: :nr, name: "Southern Ndebele"},
    %{bcp_47: :st, name: "Southern Sotho"},
    %{bcp_47: :es, name: "Spanish"},
    %{bcp_47: :su, name: "Sundanese"},
    %{bcp_47: :sw, name: "Swahili"},
    %{bcp_47: :ss, name: "Swati"},
    %{bcp_47: :sv, name: "Swedish"},
    %{bcp_47: :tl, name: "Tagalog"},
    %{bcp_47: :ty, name: "Tahitian"},
    %{bcp_47: :tg, name: "Tajik"},
    %{bcp_47: :ta, name: "Tamil"},
    %{bcp_47: :tt, name: "Tatar"},
    %{bcp_47: :te, name: "Telugu"},
    %{bcp_47: :th, name: "Thai"},
    %{bcp_47: :bo, name: "Tibetan Standard"},
    %{bcp_47: :ti, name: "Tigrinya"},
    %{bcp_47: :to, name: "Tonga"},
    %{bcp_47: :ts, name: "Tsonga"},
    %{bcp_47: :tn, name: "Tswana"},
    %{bcp_47: :tr, name: "Turkish"},
    %{bcp_47: :tk, name: "Turkmen"},
    %{bcp_47: :tw, name: "Twi"},
    %{bcp_47: :uk, name: "Ukrainian"},
    %{bcp_47: :ur, name: "Urdu"},
    %{bcp_47: :ug, name: "Uyghur"},
    %{bcp_47: :uz, name: "Uzbek"},
    %{bcp_47: :ve, name: "Venda"},
    %{bcp_47: :vi, name: "Vietnamese"},
    %{bcp_47: :vo, name: "Volapük"},
    %{bcp_47: :wa, name: "Walloon"},
    %{bcp_47: :cy, name: "Welsh"},
    %{bcp_47: :fy, name: "Western Frisian"},
    %{bcp_47: :wo, name: "Wolof"},
    %{bcp_47: :xh, name: "Xhosa"},
    %{bcp_47: :yi, name: "Yiddish"},
    %{bcp_47: :yo, name: "Yoruba"},
    %{bcp_47: :za, name: "Zhuang"},
    %{bcp_47: :zu, name: "Zulu"},
    %{bcp_47: :ase, name: "American Sign Language"},
    %{bcp_47: :bzs, name: "Brazilian Sign Language"},
    %{bcp_47: :bfi, name: "British Sign Language"},
    %{bcp_47: :csl, name: "Chinese Sign Language"},
    %{bcp_47: :dse, name: "Dutch Sign Language"},
    %{bcp_47: :fsl, name: "French Sign Language"},
    %{bcp_47: :gsg, name: "German Sign Language"},
    %{bcp_47: :ins, name: "Indo-Pakistani Sign Language"},
    %{bcp_47: :inl, name: "Indonesian Sign Language"},
    %{bcp_47: :jsl, name: "Japanese Sign Language"},
    %{bcp_47: :kvk, name: "Korean Sign Language"},
    %{bcp_47: :mfs, name: "Mexican Sign Language"},
    %{bcp_47: :psr, name: "Portuguese Sign Language"},
    %{bcp_47: :rsl, name: "Russian Sign Language"},
    %{bcp_47: :ssp, name: "Spanish Sign Language"}
  ]

  @language_codes Enum.map(@languages, & &1[:bcp_47])
  @language_names Enum.map(@languages, & &1[:name])

  def list(), do: @languages
  def list(:bcp_47), do: @language_codes
  def list(:name), do: @language_names
end
