defmodule Flirtual.Languages do
  # https://en.wikipedia.org/wiki/ISO_639-1
  # https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

  @languages [
    %{iso_639_1: "ab", name: "Abkhazian"},
    %{iso_639_1: "aa", name: "Afar"},
    %{iso_639_1: "af", name: "Afrikaans"},
    %{iso_639_1: "ak", name: "Akan"},
    %{iso_639_1: "sq", name: "Albanian"},
    %{iso_639_1: "am", name: "Amharic"},
    %{iso_639_1: "ar", name: "Arabic"},
    %{iso_639_1: "an", name: "Aragonese"},
    %{iso_639_1: "hy", name: "Armenian"},
    %{iso_639_1: "as", name: "Assamese"},
    %{iso_639_1: "av", name: "Avaric"},
    %{iso_639_1: "ae", name: "Avestan"},
    %{iso_639_1: "ay", name: "Aymara"},
    %{iso_639_1: "az", name: "Azerbaijani"},
    %{iso_639_1: "bm", name: "Bambara"},
    %{iso_639_1: "ba", name: "Bashkir"},
    %{iso_639_1: "eu", name: "Basque"},
    %{iso_639_1: "be", name: "Belarusian"},
    %{iso_639_1: "bn", name: "Bengali"},
    %{iso_639_1: "bi", name: "Bislama"},
    %{iso_639_1: "bs", name: "Bosnian"},
    %{iso_639_1: "br", name: "Breton"},
    %{iso_639_1: "bg", name: "Bulgarian"},
    %{iso_639_1: "my", name: "Burmese"},
    %{iso_639_1: "ca", name: "Catalan, Valencian"},
    %{iso_639_1: "ch", name: "Chamorro"},
    %{iso_639_1: "ce", name: "Chechen"},
    %{iso_639_1: "ny", name: "Chichewa, Chewa, Nyanja"},
    %{iso_639_1: "zh", name: "Chinese"},
    %{iso_639_1: "cu", name: "Church Slavonic, Old Slavonic, Old Church Slavonic"},
    %{iso_639_1: "cv", name: "Chuvash"},
    %{iso_639_1: "kw", name: "Cornish"},
    %{iso_639_1: "co", name: "Corsican"},
    %{iso_639_1: "cr", name: "Cree"},
    %{iso_639_1: "hr", name: "Croatian"},
    %{iso_639_1: "cs", name: "Czech"},
    %{iso_639_1: "da", name: "Danish"},
    %{iso_639_1: "dv", name: "Divehi, Dhivehi, Maldivian"},
    %{iso_639_1: "nl", name: "Dutch, Flemish"},
    %{iso_639_1: "dz", name: "Dzongkha"},
    %{iso_639_1: "en", name: "English"},
    %{iso_639_1: "eo", name: "Esperanto"},
    %{iso_639_1: "et", name: "Estonian"},
    %{iso_639_1: "ee", name: "Ewe"},
    %{iso_639_1: "fo", name: "Faroese"},
    %{iso_639_1: "fj", name: "Fijian"},
    %{iso_639_1: "fi", name: "Finnish"},
    %{iso_639_1: "fr", name: "French"},
    %{iso_639_1: "fy", name: "Western Frisian"},
    %{iso_639_1: "ff", name: "Fulah"},
    %{iso_639_1: "gd", name: "Gaelic, Scottish Gaelic"},
    %{iso_639_1: "gl", name: "Galician"},
    %{iso_639_1: "lg", name: "Ganda"},
    %{iso_639_1: "ka", name: "Georgian"},
    %{iso_639_1: "de", name: "German"},
    %{iso_639_1: "el", name: "Greek, Modern (1453–)"},
    %{iso_639_1: "kl", name: "Kalaallisut, Greenlandic"},
    %{iso_639_1: "gn", name: "Guarani"},
    %{iso_639_1: "gu", name: "Gujarati"},
    %{iso_639_1: "ht", name: "Haitian, Haitian Creole"},
    %{iso_639_1: "ha", name: "Hausa"},
    %{iso_639_1: "he", name: "Hebrew"},
    %{iso_639_1: "hz", name: "Herero"},
    %{iso_639_1: "hi", name: "Hindi"},
    %{iso_639_1: "ho", name: "Hiri Motu"},
    %{iso_639_1: "hu", name: "Hungarian"},
    %{iso_639_1: "is", name: "Icelandic"},
    %{iso_639_1: "io", name: "Ido"},
    %{iso_639_1: "ig", name: "Igbo"},
    %{iso_639_1: "id", name: "Indonesian"},
    %{iso_639_1: "ia", name: "Interlingua (International Auxiliary Language Association)"},
    %{iso_639_1: "ie", name: "Interlingue, Occidental"},
    %{iso_639_1: "iu", name: "Inuktitut"},
    %{iso_639_1: "ik", name: "Inupiaq"},
    %{iso_639_1: "ga", name: "Irish"},
    %{iso_639_1: "it", name: "Italian"},
    %{iso_639_1: "ja", name: "Japanese"},
    %{iso_639_1: "jv", name: "Javanese"},
    %{iso_639_1: "kn", name: "Kannada"},
    %{iso_639_1: "kr", name: "Kanuri"},
    %{iso_639_1: "ks", name: "Kashmiri"},
    %{iso_639_1: "kk", name: "Kazakh"},
    %{iso_639_1: "km", name: "Central Khmer"},
    %{iso_639_1: "ki", name: "Kikuyu, Gikuyu"},
    %{iso_639_1: "rw", name: "Kinyarwanda"},
    %{iso_639_1: "ky", name: "Kirghiz, Kyrgyz"},
    %{iso_639_1: "kv", name: "Komi"},
    %{iso_639_1: "kg", name: "Kongo"},
    %{iso_639_1: "ko", name: "Korean"},
    %{iso_639_1: "kj", name: "Kuanyama, Kwanyama"},
    %{iso_639_1: "ku", name: "Kurdish"},
    %{iso_639_1: "lo", name: "Lao"},
    %{iso_639_1: "la", name: "Latin"},
    %{iso_639_1: "lv", name: "Latvian"},
    %{iso_639_1: "li", name: "Limburgan, Limburger, Limburgish"},
    %{iso_639_1: "ln", name: "Lingala"},
    %{iso_639_1: "lt", name: "Lithuanian"},
    %{iso_639_1: "lu", name: "Luba-Katanga"},
    %{iso_639_1: "lb", name: "Luxembourgish, Letzeburgesch"},
    %{iso_639_1: "mk", name: "Macedonian"},
    %{iso_639_1: "mg", name: "Malagasy"},
    %{iso_639_1: "ms", name: "Malay"},
    %{iso_639_1: "ml", name: "Malayalam"},
    %{iso_639_1: "mt", name: "Maltese"},
    %{iso_639_1: "gv", name: "Manx"},
    %{iso_639_1: "mi", name: "Maori"},
    %{iso_639_1: "mr", name: "Marathi"},
    %{iso_639_1: "mh", name: "Marshallese"},
    %{iso_639_1: "mn", name: "Mongolian"},
    %{iso_639_1: "na", name: "Nauru"},
    %{iso_639_1: "nv", name: "Navajo, Navaho"},
    %{iso_639_1: "nd", name: "North Ndebele"},
    %{iso_639_1: "nr", name: "South Ndebele"},
    %{iso_639_1: "ng", name: "Ndonga"},
    %{iso_639_1: "ne", name: "Nepali"},
    %{iso_639_1: "no", name: "Norwegian"},
    %{iso_639_1: "nb", name: "Norwegian Bokmål"},
    %{iso_639_1: "nn", name: "Norwegian Nynorsk"},
    %{iso_639_1: "ii", name: "Sichuan Yi, Nuosu"},
    %{iso_639_1: "oc", name: "Occitan"},
    %{iso_639_1: "oj", name: "Ojibwa"},
    %{iso_639_1: "or", name: "Oriya"},
    %{iso_639_1: "om", name: "Oromo"},
    %{iso_639_1: "os", name: "Ossetian, Ossetic"},
    %{iso_639_1: "pi", name: "Pali"},
    %{iso_639_1: "ps", name: "Pashto, Pushto"},
    %{iso_639_1: "fa", name: "Persian"},
    %{iso_639_1: "pl", name: "Polish"},
    %{iso_639_1: "pt", name: "Portuguese"},
    %{iso_639_1: "pa", name: "Punjabi, Panjabi"},
    %{iso_639_1: "qu", name: "Quechua"},
    %{iso_639_1: "ro", name: "Romanian, Moldavian, Moldovan"},
    %{iso_639_1: "rm", name: "Romansh"},
    %{iso_639_1: "rn", name: "Rundi"},
    %{iso_639_1: "ru", name: "Russian"},
    %{iso_639_1: "se", name: "Northern Sami"},
    %{iso_639_1: "sm", name: "Samoan"},
    %{iso_639_1: "sg", name: "Sango"},
    %{iso_639_1: "sa", name: "Sanskrit"},
    %{iso_639_1: "sc", name: "Sardinian"},
    %{iso_639_1: "sr", name: "Serbian"},
    %{iso_639_1: "sn", name: "Shona"},
    %{iso_639_1: "sd", name: "Sindhi"},
    %{iso_639_1: "si", name: "Sinhala, Sinhalese"},
    %{iso_639_1: "sk", name: "Slovak"},
    %{iso_639_1: "sl", name: "Slovenian"},
    %{iso_639_1: "so", name: "Somali"},
    %{iso_639_1: "st", name: "Southern Sotho"},
    %{iso_639_1: "es", name: "Spanish, Castilian"},
    %{iso_639_1: "su", name: "Sundanese"},
    %{iso_639_1: "sw", name: "Swahili"},
    %{iso_639_1: "ss", name: "Swati"},
    %{iso_639_1: "sv", name: "Swedish"},
    %{iso_639_1: "tl", name: "Tagalog"},
    %{iso_639_1: "ty", name: "Tahitian"},
    %{iso_639_1: "tg", name: "Tajik"},
    %{iso_639_1: "ta", name: "Tamil"},
    %{iso_639_1: "tt", name: "Tatar"},
    %{iso_639_1: "te", name: "Telugu"},
    %{iso_639_1: "th", name: "Thai"},
    %{iso_639_1: "bo", name: "Tibetan"},
    %{iso_639_1: "ti", name: "Tigrinya"},
    %{iso_639_1: "to", name: "Tonga (Tonga Islands)"},
    %{iso_639_1: "ts", name: "Tsonga"},
    %{iso_639_1: "tn", name: "Tswana"},
    %{iso_639_1: "tr", name: "Turkish"},
    %{iso_639_1: "tk", name: "Turkmen"},
    %{iso_639_1: "tw", name: "Twi"},
    %{iso_639_1: "ug", name: "Uighur, Uyghur"},
    %{iso_639_1: "uk", name: "Ukrainian"},
    %{iso_639_1: "ur", name: "Urdu"},
    %{iso_639_1: "uz", name: "Uzbek"},
    %{iso_639_1: "ve", name: "Venda"},
    %{iso_639_1: "vi", name: "Vietnamese"},
    %{iso_639_1: "vo", name: "Volapük"},
    %{iso_639_1: "wa", name: "Walloon"},
    %{iso_639_1: "cy", name: "Welsh"},
    %{iso_639_1: "wo", name: "Wolof"},
    %{iso_639_1: "xh", name: "Xhosa"},
    %{iso_639_1: "yi", name: "Yiddish"},
    %{iso_639_1: "yo", name: "Yoruba"},
    %{iso_639_1: "za", name: "Zhuang, Chuang"},
    %{iso_639_1: "zu", name: "Zulu"}
  ]

  @language_codes Enum.map(@languages, & &1[:iso_639_1])
  @language_names Enum.map(@languages, & &1[:name])

  def list(), do: @languages
  def list(:iso_639_1), do: @language_codes
  def list(:name), do: @language_names
end
