// Generated by Wrangler by running `wrangler types --include-runtime=false`
declare namespace Cloudflare {
	interface Env {
		API_ORIGIN: string;
		DESTINATION_ORIGIN: string;
	}
}
interface Env extends Cloudflare.Env {}
