#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Don't try to lint deleted files
filter_existing() {
    while read -r file; do
        [ -e "$file" ] && echo "$file"
    done
}

# Pre-commit hook for linting and formatting apps.
if ! git diff --cached --quiet -- "apps/api/*"; then
    git diff --name-only --cached | grep -E ".*\.(ex|exs)$" | filter_existing | xargs -I {} sh -c 'mix format "{}"; git add "{}"'
    cd apps/api
    #mix check --only formatter --only credo
    cd ..
fi

if ! git diff --cached --quiet -- "apps/frontend/*"; then
    cd apps/frontend
    #pnpm lint-staged
    cd ..
fi
