#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Pre-commit hook for linting and formatting apps.
if ! git diff --cached --quiet -- "apps/api/*"; then
    git diff --name-only --cached | grep -E ".*\.(ex|exs)$" | xargs -d $'\n' sh -c 'for arg do mix format "$arg"; git add "$arg"; done'
    cd apps/api
    #mix check --only formatter --only credo
    cd ..
fi

if ! git diff --cached --quiet -- "apps/frontend/*"; then
    cd apps/frontend
    pnpm lint-staged
    cd ..
fi
