require_relative '../../node_modules/.pnpm/@capacitor+ios@6.2.0_@capacitor+core@6.2.0/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@6.2.0_@capacitor+core@6.2.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@6.2.0_@capacitor+core@6.2.0/node_modules/@capacitor/ios'
  pod 'AashuDubeyCapacitorStatusbarSafeArea', :path => '../../node_modules/.pnpm/@aashu-dubey+capacitor-statusbar-safe-area@3.0.0_@capacitor+core@6.2.0/node_modules/@aashu-dubey/capacitor-statusbar-safe-area'
  pod 'CapacitorCommunityInAppReview', :path => '../../node_modules/.pnpm/@capacitor-community+in-app-review@6.0.0_@capacitor+core@6.2.0/node_modules/@capacitor-community/in-app-review'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@6.0.2_@capacitor+core@6.2.0/node_modules/@capacitor/app'
  pod 'CapacitorClipboard', :path => '../../node_modules/.pnpm/@capacitor+clipboard@6.0.2_@capacitor+core@6.2.0/node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@6.0.2_@capacitor+core@6.2.0/node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../node_modules/.pnpm/@capacitor+dialog@6.0.2_@capacitor+core@6.2.0/node_modules/@capacitor/dialog'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@6.0.3_@capacitor+core@6.2.0/node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/.pnpm/@capacitor+local-notifications@6.1.1_@capacitor+core@6.2.0/node_modules/@capacitor/local-notifications'
  pod 'CapacitorPreferences', :path => '../../node_modules/.pnpm/@capacitor+preferences@6.0.3_@capacitor+core@6.2.0/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.pnpm/@capacitor+push-notifications@6.0.3_@capacitor+core@6.2.0/node_modules/@capacitor/push-notifications'
  pod 'CapacitorScreenOrientation', :path => '../../node_modules/.pnpm/@capacitor+screen-orientation@6.0.3_@capacitor+core@6.2.0/node_modules/@capacitor/screen-orientation'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@6.0.3_@capacitor+core@6.2.0/node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@6.0.2_@capacitor+core@6.2.0/node_modules/@capacitor/status-bar'
  pod 'CapacitorToast', :path => '../../node_modules/.pnpm/@capacitor+toast@6.0.3_@capacitor+core@6.2.0/node_modules/@capacitor/toast'
  pod 'CapawesomeTeamCapacitorDatetimePicker', :path => '../../node_modules/.pnpm/@capawesome-team+capacitor-datetime-picker@6.0.0_@capacitor+core@6.2.0/node_modules/@capawesome-team/capacitor-datetime-picker'
  pod 'CapawesomeCapacitorAppUpdate', :path => '../../node_modules/.pnpm/@capawesome+capacitor-app-update@6.1.0_@capacitor+core@6.2.0/node_modules/@capawesome/capacitor-app-update'
  pod 'CapgoInappbrowser', :path => '../../node_modules/.pnpm/@capgo+inappbrowser@6.9.18_@capacitor+core@6.2.0/node_modules/@capgo/inappbrowser'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/.pnpm/@revenuecat+purchases-capacitor@8.0.0-beta.4_@capacitor+core@6.2.0/node_modules/@revenuecat/purchases-capacitor'
end

target 'Flirtual' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
