services:
  postgres:
    image: postgres:17.7-alpine
    shm_size: 256m
    command: postgres -N 500
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  manticore:
    image: manticoresearch/manticore:28.4.4
    restart: always
    mem_limit: 2g
    volumes:
      - manticore_data:/var/lib/manticore
    ports:
      - 9306:9306
      - 9308:9308
volumes:
  postgres_data:
  manticore_data:
