services:
  postgres:
    # renovate: datasource=docker depName=flyio/postgres-flex
    image: postgres:17.7-alpine
    shm_size: 256m
    command: postgres -N 500
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  manticore:
    image: manticoresearch/manticore:28.6.6@sha256:341f333906fb2183fe585ad66de3486f372b2bbdd39e0e001d280a54f06d893a
    restart: always
    mem_limit: 2g
    volumes:
      - manticore_data:/var/lib/manticore
    ports:
      - 9306:9306
      - 9308:9308
volumes:
  postgres_data:
  manticore_data:
