name: Deploy API
on:
  push:
    branches: [ "production" ]
    paths: [ "apps/api/**", ".github/workflows/deploy-api.yaml" ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          curl -sL https://sentry.io/get-cli/ | bash
          
          GIT_COMMIT_SHA=$(git rev-parse HEAD)
          flyctl deploy --remote-only --env GIT_COMMIT_SHA="$GIT_COMMIT_SHA"
        working-directory: ./apps/api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: flirtual
          SENTRY_PROJECT: api