on:
  push:
    paths: [ "apps/frontend/**", ".github/workflows/frontend.yaml" ]
  pull_request:
    paths: [ "apps/frontend/**", ".github/workflows/frontend.yaml" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v5

      - run: echo "::add-matcher::.github/annotation-eslint.json"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: apps/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: ESLint
        run: ./node_modules/.bin/eslint -f stylish

  typescript:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v5

      - run: echo "::add-matcher::.github/annotation-typescript.json"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: apps/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript
        run: |
          ./node_modules/.bin/tsc --pretty false --noEmit | sed -E "s#^.+\(.+\): error TS.+\$#$PWD/\0#"
          exit ${PIPESTATUS[0]}

  release:
    strategy:
      matrix:
        environment: [production, canary]
        exclude:
          - environment: ${{ github.ref != 'refs/heads/production' && 'production' || null }}
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: apps/frontend
    env:
      VITE_TURNSTILE_SITE_KEY: ${{ vars.VITE_TURNSTILE_SITE_KEY }}
      VITE_TALKJS_APP_ID: ${{ vars.VITE_TALKJS_APP_ID }}
      VITE_RC_APPL_PUBLIC_KEY: ${{ vars.VITE_RC_APPL_PUBLIC_KEY }}
      VITE_RC_GOOG_PUBLIC_KEY: ${{ vars.VITE_RC_GOOG_PUBLIC_KEY }}
      VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
      VITE_SENTRY_ORGANIZATION: ${{ vars.VITE_SENTRY_ORGANIZATION }}
      VITE_SENTRY_PROJECT_ID: ${{ vars.VITE_SENTRY_PROJECT_ID }}
      VITE_SENTRY_REPORT_TO: ${{ vars.VITE_SENTRY_REPORT_TO }}
      VITE_CLOUDFLARE_BEACON_ID: ${{ vars.VITE_CLOUDFLARE_BEACON_ID }}
      VITE_CANNY_APP_ID: ${{ vars.VITE_CANNY_APP_ID }}
      VITE_FRESHWORKS_WIDGET_ID: ${{ vars.VITE_FRESHWORKS_WIDGET_ID }}
      VITE_UPPY_COMPANION_URL: ${{ vars.VITE_UPPY_COMPANION_URL }}
      VITE_UPPY_BUCKET_ORIGIN: ${{ vars.VITE_UPPY_BUCKET_ORIGIN }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_ORIGIN: ${{ vars.VITE_ORIGIN }}
      VITE_PICO_APP_ID: ${{ vars.VITE_PICO_APP_ID }}
      VITE_PLATFORM_OVERRIDE: ${{ vars.VITE_PLATFORM_OVERRIDE }}
      VITE_BUCKET_CONTENT_ORIGIN: ${{ vars.VITE_BUCKET_CONTENT_ORIGIN }}
      VITE_BUCKET_UPLOADS_ORIGIN: ${{ vars.VITE_BUCKET_UPLOADS_ORIGIN }}
      VITE_BUCKET_UPLOADS_SIGNED_ORIGIN: ${{ vars.VITE_BUCKET_UPLOADS_SIGNED_ORIGIN }}

      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: apps/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - run: pnpm release
