name: Renovate
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:
    inputs:
      repoCache:
        description: Reset or disable the repository cache?
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset
  issues:
    types: [edited]
  pull_request:
    types: [edited]
permissions:
  contents: read
concurrency:
  group: renovate
env:
  cache_dir: /tmp/renovate/cache/renovate/repository
  cache_key: renovate-cache
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    if: >-
      (github.event_name != 'issues' && github.event_name != 'pull_request')
      || (github.event.sender.id != 317127550
      && (github.event.issue.user.id == 317127550
      || github.event.pull_request.user.id == 317127550))
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.RENOVATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - name: Restore repository cache
        id: cache-restore
        if: github.event.inputs.repoCache != 'disabled' && github.event.inputs.repoCache != 'reset'
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ env.cache_dir }}
          key: ${{ env.cache_key }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache_key }}-

      # https://github.com/renovatebot/github-action#persisting-the-repository-cache
      - name: Fix restored cache ownership
        if: steps.cache-restore.outputs.cache-matched-key != ''
        run: sudo chown -R 12021:0 /tmp/renovate/

      - uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          token: ${{ steps.app-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_BINARY_SOURCE: global
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.repoCache || 'enabled' }}

      - name: Save repository cache
        if: github.event.inputs.repoCache != 'disabled' && steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ env.cache_dir }}
          key: ${{ env.cache_key }}-${{ github.run_id }}-${{ github.run_attempt }}
