name: Root
on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  root:
    name: Root
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          runtime: node@24.20.0
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter flirtual

      - name: Lint
        run: pnpm lint
