on:
  push:
    branches: [main, production]
    paths: &paths
      - apps/api/**
      - .github/workflows/sobelow.yaml
  pull_request:
    paths: *paths
  schedule:
    - cron: 13 19 * * 6
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze (elixir)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run Sobelow
        uses: sobelow/action@4c2cc216597acef2c5f8b4b2e49ad591be36ce36 # v1.2.0
        with:
          flags: --root apps/api --skip

      - name: Upload results
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        with:
          sarif_file: results.sarif
          category: /language:elixir
